# Nom du workflow
name: React-CI-CD

# Déclencheur => trigger (flux de travail)
on:
  push:
    branches: [main] # déclencher a chaque push sur la branche main

# Les jobs sont des taches a exécuter
jobs:
  build-and-deploy:
    # Environnement d'execution des taches successives
    runs-on: ubuntu-latest # dernière version de ubuntu linux

    steps:
      # 1. Récupérer les sources du dépôt GitHub concerné
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Installer Node.js dans le conteneur GitHub Actions
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: npm

      # 3. Installer les dépendances
      - name: Install dependencies
        run: npm install # "npm ci" est plus rapide et strict que "npm install" pour la CI

      # 4. Vérification de la qualité du code (Linter / ESLint)
      - name: Run Linter (ESLint)
        run: npm run lint --if-present
        # L'option --if-present évite de faire planter le script si la commande n'est pas encore configurée.

      # 5. Exécuter les tests unitaires
      - name: Run tests
        run: npm test -- --watchAll=false --passWithNoTests

      # 6. Compiler l'application pour la production (Génère le dossier build ou dist)
      - name: Build Application
        run: npm run build

      # 7. Déployer sur GitHub Pages (S'exécute uniquement si le build et les tests réussissent) ...
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Remplace par "dist" si tu utilises Vite au lieu de Create React App
          branch: gh-pages

      # npm ci au lieu de npm install (Clean Install)
